### ISSUE TITLE
"Budget" vs Fiscal vs Spending

### ISSUE THREAD

**Issue by rgrp** [openspending/budget-data-package#17]
I note that the "budget" data package is also suitable for publishing spending information like the information published by UK departments and local bodies (though this is not obviously budget-related data).

Do we need to tweak naming or, at least, make this clear in the introduction?

**Comment by rgrp** [comment]
OK, after further discussion with GIFT and stakeholders there the view is to rename to (Open) "Fiscal Data Package". So plan to implement that soon ....

**Comment by jrovegno** [comment]
I'm sorry if my message is off-topic, but I think that this standard is the first iteration of a narrowed topic "government accountability" but in the future on the next iteration you will be needed a broader topic "social accountability", because NGO, Political Parties. corporations and other organizations they are all connected.

My opinion is that what matters is the "flow of resource", then the package should be called "Accounting Data Package"

And I say "resource" and not "money" because it is sometimes more effective bookkeeping of resources rather than the price of something, for example fishing quotas, water, energy, etc.

**Comment by pudo** [comment]
@jrovegno If you're looking for a more general accounting data standard, it's also worth checking out [XBRL](https://en.wikipedia.org/wiki/XBRL). It's "the law" in both the US and UK and several other places.
